name: flutter_stone_payment
description: "Plugin flutter que faz a integração com o SDK da stone, para pagamento com maquininhas POS"
version: 1.1.1
homepage: https://github.com/Luiz-Carlos-de-Lima/flutter_stone_payment

environment:
  sdk: ^3.6.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: br.com.jclan.alphaxStonePayment.flutter_stone_payment
        pluginClass: FlutterStonePaymentPlugin
